""" Create associate_wording_severity table

Revision ID: 15efa48238d6
Revises: 4f7b1b385510
Create Date: 2015-01-23 14:00:01.577083

"""

# revision identifiers, used by Alembic.
revision = '15efa48238d6'
down_revision = '4f7b1b385510'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_wording_severity',
    sa.Column('wording_id', postgresql.UUID(), nullable=False),
    sa.Column('severity_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['severity_id'], ['severity.id'], ),
    sa.ForeignKeyConstraint(['wording_id'], ['wording.id'], ),
    sa.PrimaryKeyConstraint('wording_id', 'severity_id', name='wording_severity_pk')
    )

    connection = op.get_bind()
    connection.execute('insert into  wording (created_at, id, key, value) '
                       'select created_at , id ,  \'long\', wording from severity')
    connection.execute('insert into  associate_wording_severity (severity_id, wording_id) '
                       'select id , id from severity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associate_wording_severity')
    ### end Alembic commands ###
