"""Assocation disruptions-tags

Revision ID: 1894217a6b3f
Revises: 51c1d76c3cc5
Create Date: 2014-07-02 09:16:00.517059

"""

# revision identifiers, used by Alembic.
revision = '1894217a6b3f'
down_revision = '51c1d76c3cc5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('severity',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('wording', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('severity')
    ### end Alembic commands ###
