"""Add disruption_status enum and status field in disruption

Revision ID: 1c4e076fd226
Revises: 3dfda3dab905
Create Date: 2014-06-12 10:58:51.852896

"""

# revision identifiers, used by Alembic.
revision = '1c4e076fd226'
down_revision = '3dfda3dab905'

from alembic import op
import sqlalchemy as sa
from migrations.utils import index_exists

disruption_status = sa.Enum('published', 'archived', name='disruption_status')

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    disruption_status.create(op.get_bind())
    op.add_column('disruption', sa.Column('status', disruption_status, nullable=False, server_default='published', index=True))
    if not index_exists('ix_disruption_status'):
        op.create_index('ix_disruption_status', 'disruption', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disruption_status', 'disruption')
    op.drop_column('disruption', 'status')
    disruption_status.drop(op.get_bind())
    ### end Alembic commands ###
