"""Assocation disruptions-tags

Revision ID: 22b6f005f203
Revises: 32ea230d67a8
Create Date: 2014-07-30 11:33:14.842719

"""

# revision identifiers, used by Alembic.
revision = '22b6f005f203'
down_revision = '32ea230d67a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_disruption_tag',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('disruption_id', postgresql.UUID(), nullable=True),
    sa.Column('tag_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], [u'disruption.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disruption_id', 'tag_id')
    )
    op.create_index('ix_associate_disruption_tag_disruption_id', 'associate_disruption_tag', ['disruption_id'], unique=False)
    op.create_index('ix_associate_disruption_tag_tag_id', 'associate_disruption_tag', ['tag_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_associate_disruption_tag_tag_id', 'associate_disruption_tag')
    op.drop_index('ix_associate_disruption_tag_disruption_id', 'associate_disruption_tag')
    op.drop_table('associate_disruption_tag')
    ### end Alembic commands ###
