"""StopPoint added in object type

Revision ID: 22ced1088b04
Revises: fcd3c78a6ec
Create Date: 2015-05-11 13:57:47.806061

"""

# revision identifiers, used by Alembic.
revision = '22ced1088b04'
down_revision = 'fcd3c78a6ec'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")  # See https://bitbucket.org/zzzeek/alembic/issue/123
    op.execute("ALTER TYPE pt_object_type ADD VALUE 'stop_point'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE pt_object ALTER COLUMN type TYPE text")
    op.execute("DELETE FROM pt_object WHERE  type='stop_point'")
    op.execute("DROP TYPE pt_object_type")
    op.execute("CREATE TYPE pt_object_type AS ENUM ('network', 'stop_area', 'line', 'line_section','route')")
    op.execute("ALTER TABLE pt_object ALTER COLUMN type TYPE pt_object_type USING type::pt_object_type")
    ### end Alembic commands ###
