"""Add table ptobject

Revision ID: 23a41b087b24
Revises: 6f3aadb613f
Create Date: 2014-07-03 11:27:01.385957

"""

# revision identifiers, used by Alembic.
revision = '23a41b087b24'
down_revision = '6f3aadb613f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pt_object',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('object_id', postgresql.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    #Represents code (uri) of PTobject
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('impact_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], [u'impact.id'] ),
    sa.PrimaryKeyConstraint('object_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pt_object')
    ### end Alembic commands ###
