"""Adding 2 new channels types

Revision ID: 2c160dff136a
Revises: e33962db5d9
Create Date: 2017-07-31 10:34:57.606834

"""

# revision identifiers, used by Alembic.
revision = '2c160dff136a'
down_revision = 'e33962db5d9'

from alembic import op

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")  # See https://bitbucket.org/zzzeek/alembic/issue/123
    op.execute("ALTER TYPE channel_type_enum ADD VALUE 'title'")
    op.execute("ALTER TYPE channel_type_enum ADD VALUE 'beacon'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE channel_type ALTER COLUMN name TYPE text")
    op.execute("DELETE FROM channel_type WHERE name='title' OR name='beacon'")
    op.execute("DROP TYPE channel_type_enum CASCADE")
    op.execute("CREATE TYPE channel_type_enum AS ENUM ( 'web', 'sms', 'email', 'mobile', 'notification', 'twitter', 'facebook')")
    op.execute("ALTER TABLE channel_type ALTER COLUMN name TYPE channel_type_enum USING name::channel_type_enum")
    ### end Alembic commands ###
