"""associate_disruption_tag table added

Revision ID: 395d2d1824a9
Revises: 32ea230d67a8
Create Date: 2014-07-31 16:57:43.384630

"""

# revision identifiers, used by Alembic.
revision = '395d2d1824a9'
down_revision = '32ea230d67a8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_disruption_tag',
    sa.Column('tag_id', postgresql.UUID(), nullable=True),
    sa.Column('disruption_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruption.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'disruption_id', name='tag_disruption_pk')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associate_disruption_tag')
    ### end Alembic commands ###
