"""Associate route line_section

Revision ID: 3963a075ac12
Revises: 5a14937a07a
Create Date: 2014-09-05 11:49:21.109966

"""

# revision identifiers, used by Alembic.
revision = '3963a075ac12'
down_revision = '5a14937a07a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_line_section_route_object',
    sa.Column('line_section_id', postgresql.UUID(), nullable=True),
    sa.Column('route_object_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['line_section_id'], ['line_section.id'], ),
    sa.ForeignKeyConstraint(['route_object_id'], ['pt_object.id'], ),
    sa.PrimaryKeyConstraint('line_section_id', 'route_object_id', name='line_section_route_object_pk')
    )
    op.execute("COMMIT")  # See https://bitbucket.org/zzzeek/alembic/issue/123
    op.execute("ALTER TYPE pt_object_type ADD VALUE 'route'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associate_line_section_route_object')
    op.execute("ALTER TABLE pt_object ALTER COLUMN type TYPE text")
    op.execute("DELETE FROM pt_object WHERE  type='route'")
    op.execute("DROP TYPE pt_object_type")
    op.execute("CREATE TYPE pt_object_type AS ENUM ('network', 'stop_area', 'line', 'line_section')")
    op.execute("ALTER TABLE pt_object ALTER COLUMN type TYPE pt_object_type USING type::pt_object_type")
    ### end Alembic commands ###
