"""create table channel

Revision ID: 3cd91baeb131
Revises: 99f668ee548
Create Date: 2014-07-08 14:37:03.887168

"""

# revision identifiers, used by Alembic.
revision = '3cd91baeb131'
down_revision = '99f668ee548'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    ### end Alembic commands ###
