"""Add localization_id in disruption

Revision ID: 44f79c38de76
Revises: 3c0a7038a8c
Create Date: 2014-07-17 10:59:51.639951

"""

# revision identifiers, used by Alembic.
revision = '44f79c38de76'
down_revision = '3c0a7038a8c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disruption', sa.Column('localization_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disruption', 'localization_id')
    ### end Alembic commands ###
