"""Optimization create index

Revision ID: 45ead599829a
Revises: 4cfc9a0eff57
Create Date: 2014-07-24 11:50:21.632474

"""

# revision identifiers, used by Alembic.
revision = '45ead599829a'
down_revision = '4cfc9a0eff57'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_application_periods_impact_id', 'application_periods', ['impact_id'], unique=False)
    op.create_index('ix_pt_object_impact_id', 'pt_object', ['impact_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pt_object_impact_id', 'pt_object')
    op.drop_index('ix_application_periods_impact_id', 'application_periods')
    ### end Alembic commands ###
