"""Add Causes tables

Revision ID: 4adbb49a02f0
Revises: 405df13d41fe
Create Date: 2014-07-03 10:46:25.306488

"""

# revision identifiers, used by Alembic.
revision = '4adbb49a02f0'
down_revision = '405df13d41fe'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cause',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('wording', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cause')
    ### end Alembic commands ###
