"""table message

Revision ID: 4cfc9a0eff57
Revises: 44f79c38de76
Create Date: 2014-07-18 17:24:56.476953

"""

# revision identifiers, used by Alembic.
revision = '4cfc9a0eff57'
down_revision = '44f79c38de76'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('impact_id', postgresql.UUID(), nullable=True),
    sa.Column('channel_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], [u'channel.id'], ),
    sa.ForeignKeyConstraint(['impact_id'], [u'impact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    ### end Alembic commands ###
