"""empty message

Revision ID: 4ddbd7d83e6a
Revises: 1b9a20f9a38f
Create Date: 2015-01-16 16:15:26.335065

"""

# revision identifiers, used by Alembic.
revision = '4ddbd7d83e6a'
down_revision = '1b9a20f9a38f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('client_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], [u'client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'client_id', name='category_name_client_id_key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    ### end Alembic commands ###
