""" Create table wording

Revision ID: 4f7b1b385510
Revises: 4ddbd7d83e6a
Create Date: 2015-01-19 15:16:51.245609

"""

# revision identifiers, used by Alembic.
revision = '4f7b1b385510'
down_revision = '4ddbd7d83e6a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wording',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associate_wording_cause',
    sa.Column('wording_id', postgresql.UUID(), nullable=False),
    sa.Column('cause_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.id'], ),
    sa.ForeignKeyConstraint(['wording_id'], ['wording.id'], ),
    sa.PrimaryKeyConstraint('wording_id', 'cause_id', name='wording_cause_pk')
    )
    op.add_column(u'cause', sa.Column('category_id', postgresql.UUID(), nullable=True))

    connection = op.get_bind()
    rows = connection.execute('select created_at as created_at, id as id, '
                              'wording as value, \'external_long\' as key, category, client_id from cause')
    for row in rows:
        op.execute("insert into  wording (created_at, id, key, value) values(\'{}\', \'{}\', \'{}\', \'{}\')".
                   format(row['created_at'], row['id'], row['key'], row['value']))
        op.execute("insert into  associate_wording_cause (wording_id, cause_id) values(\'{}\', \'{}\')".
                   format(row['id'], row['id']))
        if row['category'] and row['category'] != '':
            op.execute("insert into category (id, name, created_at, client_id, is_visible) "
                       "values(\'{}\', \'{}\', \'{}\', \'{}\', {})".
                       format(row['id'], row['category'], row['created_at'], row['client_id'], True))
            op.execute("update cause set category_id= \'{}\' where id=\'{}\' ".
                       format(row['id'], row['id']))

    op.drop_column(u'cause', 'category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cause', sa.Column('category', sa.Text(), nullable=True))
    connection = op.get_bind()
    connection.execute('update cause c set category=cn.name from category cn '
                       'where c.category_id=cn.id and c.category_id is not null')

    connection.execute('delete from category')

    op.drop_column(u'cause', 'category_id')
    op.drop_table('associate_wording_cause')
    op.drop_table('wording')
    ### end Alembic commands ###
