"""add publication date on disruptions

Revision ID: 51c1d76c3cc5
Revises: 1c4e076fd226
Create Date: 2014-06-24 08:57:38.453324

"""

# revision identifiers, used by Alembic.
revision = '51c1d76c3cc5'
down_revision = '1c4e076fd226'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disruption', sa.Column('end_publication_date', sa.DateTime(), nullable=True))
    op.add_column('disruption', sa.Column('start_publication_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disruption', 'start_publication_date')
    op.drop_column('disruption', 'end_publication_date')
    ### end Alembic commands ###
