"""Add a column severity_id in the table impact

Revision ID: 52beb403b32d
Revises: 3cd91baeb131
Create Date: 2014-07-09 12:14:07.192692

"""

# revision identifiers, used by Alembic.
revision = '52beb403b32d'
down_revision = '3cd91baeb131'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact', sa.Column('severity_id', postgresql.UUID(), sa.ForeignKey('severity.id')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impact', 'severity_id')
    ### end Alembic commands ###
