""" Add version column in disruption

Revision ID: 54d1cae0dd8a
Revises: 1ce3fc7b7301
Create Date: 2014-12-17 12:38:51.300840

"""

# revision identifiers, used by Alembic.
revision = '54d1cae0dd8a'
down_revision = '1ce3fc7b7301'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disruption', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disruption', 'version')
    ### end Alembic commands ###
