"""Add line in pt_object_type

Revision ID: 570f97ecea5
Revises: 45ead599829a
Create Date: 2014-07-28 15:19:01.780403

"""

# revision identifiers, used by Alembic.
revision = '570f97ecea5'
down_revision = '45ead599829a'

from alembic import op

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")  # See https://bitbucket.org/zzzeek/alembic/issue/123
    op.execute("ALTER TYPE pt_object_type ADD VALUE 'unknown'")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE pt_object ALTER COLUMN type TYPE text")
    op.execute("DROP TYPE pt_object_type")
    op.execute("CREATE TYPE pt_object_type AS ENUM ('network', 'stop_area')")
    op.execute("UPDATE pt_object SET type=NULL where type='line'")
    op.execute("ALTER TABLE pt_object ALTER COLUMN type TYPE pt_object_type USING type::pt_object_type")
    ### end Alembic commands ###
