"""Add table impact

Revision ID: 6f3aadb613f
Revises: 1894217a6b3f
Create Date: 2014-07-02 16:58:02.545151

"""

# revision identifiers, used by Alembic.
revision = '6f3aadb613f'
down_revision = '4adbb49a02f0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migrations.utils import index_exists

impact_status = sa.Enum('published', 'archived', name='impact_status')

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('disruption_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['disruption_id'], [u'disruption.id'] ),
    sa.PrimaryKeyConstraint('id')
    )
    impact_status.create(op.get_bind(), True)
    op.add_column('impact', sa.Column('status', impact_status, nullable=False, server_default='published', index=True))
    if not index_exists('ix_impact_status'):
        op.create_index('ix_impact_status', 'impact', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_impact_status', 'impact')
    op.drop_table('impact')
    impact_status.drop(op.get_bind())
    ### end Alembic commands ###
