"""DataType of columns start_date and end_date modified from datetime to date

Revision ID: fcd3c78a6ec
Revises: 2cd41e01ce4e
Create Date: 2015-04-28 13:59:46.891208

"""

# revision identifiers, used by Alembic.
revision = 'fcd3c78a6ec'
down_revision = '2cd41e01ce4e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE pattern ALTER COLUMN start_date Type date')
    op.execute('ALTER TABLE pattern ALTER COLUMN end_date TYPE date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE pattern ALTER COLUMN start_date TYPE timestamp')
    op.execute('ALTER TABLE pattern ALTER COLUMN end_date TYPE timestamp')
    ### end Alembic commands ###
